# Import relevant libraries

In [1]:
!pip install -Uqq fastbook
import fastbook
import torch

fastbook.setup_book()
from fastai.vision.all import *
from fastai.vision.widgets import *
from fastbook import *
path = Path('/storage/data/mnist_png')
Path.BASE_PATH = path

In [2]:
path = untar_data(URLs.MNIST)
Path.BASE_PATH = path
path.ls()

(#2) [Path('training'),Path('testing')]

<h1>Ingest data</h1>

In [3]:
num_list = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
num_dict = L(enumerate(num_list))

In [4]:
#test cell
num_dict, num_dict[4][1]

((#10) [(0, 'zero'),(1, 'one'),(2, 'two'),(3, 'three'),(4, 'four'),(5, 'five'),(6, 'six'),(7, 'seven'),(8, 'eight'),(9, 'nine')],
 'four')

In [5]:
def stackNums(train=True):
    num_cats = [num_dict[num][1] for num in range(0,10)]
    if train==True:
        num_path = [(path/'training'/str(num[0])).ls().sorted() for num in num_dict]
    else:
        num_path = [(path/'testing'/str(num[0])).ls().sorted() for num in num_dict]
    return num_cats, num_path

In [6]:
num_cat,num_path = stackNums()
valid_num_cat,valid_num_path = stackNums(False)

In [7]:
# test cell
num_cat,num_path,valid_num_path

(['zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine'],
 [(#5923) [Path('training/0/1.png'),Path('training/0/1000.png'),Path('training/0/10005.png'),Path('training/0/10010.png'),Path('training/0/10022.png'),Path('training/0/10025.png'),Path('training/0/10026.png'),Path('training/0/10045.png'),Path('training/0/10069.png'),Path('training/0/10071.png')...],
  (#6742) [Path('training/1/10006.png'),Path('training/1/10007.png'),Path('training/1/1002.png'),Path('training/1/10020.png'),Path('training/1/10027.png'),Path('training/1/1003.png'),Path('training/1/10040.png'),Path('training/1/10048.png'),Path('training/1/10058.png'),Path('training/1/10067.png')...],
  (#5958) [Path('training/2/10009.png'),Path('training/2/10016.png'),Path('training/2/10024.png'),Path('training/2/10029.png'),Path('training/2/10072.png'),Path('training/2/10073.png'),Path('training/2/10075.png'),Path('training/2/10078.png'),Path('training/2/10081.png'),Path('training/2/10082

# Prepare data

In [8]:
#WARNING LONG
train_0s = torch.stack([tensor(Image.open(o)) for o in num_path[0]]).float()/255
train_1s = torch.stack([tensor(Image.open(o)) for o in num_path[1]]).float()/255
train_2s = torch.stack([tensor(Image.open(o)) for o in num_path[2]]).float()/255
train_3s = torch.stack([tensor(Image.open(o)) for o in num_path[3]]).float()/255
train_4s = torch.stack([tensor(Image.open(o)) for o in num_path[4]]).float()/255
train_5s = torch.stack([tensor(Image.open(o)) for o in num_path[5]]).float()/255
train_6s = torch.stack([tensor(Image.open(o)) for o in num_path[6]]).float()/255
train_7s = torch.stack([tensor(Image.open(o)) for o in num_path[7]]).float()/255
train_8s = torch.stack([tensor(Image.open(o)) for o in num_path[8]]).float()/255
train_9s = torch.stack([tensor(Image.open(o)) for o in num_path[9]]).float()/255

>Later consider using Pandas DataFrames as a means of sorting and assigning labels

In [9]:
#WARNING LONG
valid_0s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[0]]).float()/255
valid_1s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[1]]).float()/255
valid_2s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[2]]).float()/255
valid_3s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[3]]).float()/255
valid_4s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[4]]).float()/255
valid_5s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[5]]).float()/255
valid_6s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[6]]).float()/255
valid_7s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[7]]).float()/255
valid_8s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[8]]).float()/255
valid_9s = torch.stack([tensor(Image.open(o)) for o in valid_num_path[9]]).float()/255

In [10]:
# test cell
train_0s.shape, valid_3s.shape

(torch.Size([5923, 28, 28]), torch.Size([1010, 28, 28]))

# Create training dataset

In [11]:
train_x = torch.cat([train_0s, train_1s, train_2s, train_3s, train_4s, train_5s, train_6s, train_7s, train_8s, train_9s]).view(-1, 28*28)
train_y = tensor([0]*len(train_0s) + [1]*len(train_1s) + [2]*len(train_2s) + [3]*len(train_3s) + [4]*len(train_4s) + [5]*len(train_5s) + [6]*len(train_6s) + [7]*len(train_7s) + [8]*len(train_8s) + [9]*len(train_9s)).unsqueeze(1)
dset = list(zip(train_x,train_y))

#test
train_x.shape,train_y.shape,train_y.unique()

(torch.Size([60000, 784]),
 torch.Size([60000, 1]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [12]:
#test cell
len(train_0s), train_y[5920:5925]

(5923,
 tensor([[0],
         [0],
         [0],
         [1],
         [1]]))

In [13]:
#test cell
x,y = dset[torch.randint(0, train_x.shape[0], (1,))]
x.shape,y

(torch.Size([784]), tensor([6]))

In [14]:
#test cell
fruitslist = ['apple', 'banana', 'cherry', 'date', 'elderberry']
veglist = ['artichoke', 'beetroot', 'carrot', 'daikon', 'endive']
biglist = list(zip(fruitslist,veglist))
random.shuffle(biglist)
biglist

[('date', 'daikon'),
 ('banana', 'beetroot'),
 ('cherry', 'carrot'),
 ('elderberry', 'endive'),
 ('apple', 'artichoke')]

# Create validation dataset

In [15]:
valid_x = torch.cat([valid_0s, valid_1s, valid_2s, valid_3s, valid_4s, valid_5s, valid_6s, valid_7s, valid_8s, valid_9s]).view(-1, 28*28)
valid_y = tensor([0]*len(valid_0s) + [1]*len(valid_1s) + [2]*len(valid_2s) + [3]*len(valid_3s) + [4]*len(valid_4s) + [5]*len(valid_5s) + [6]*len(valid_6s) + [7]*len(valid_7s) + [8]*len(valid_8s) + [9]*len(valid_9s)).unsqueeze(1)
valid_dset = list(zip(valid_x,valid_y))

random.shuffle(dset)
random.shuffle(valid_dset)

#test
x,y = dset[torch.randint(0, valid_x.shape[0], (1,))]
x.shape,y

(torch.Size([784]), tensor([5]))

# Create dataloaders

In [16]:
dl = DataLoader(dset, batch_size=256, shuffle=True)
valid_dl = DataLoader(valid_dset, batch_size=256)

#test
xbOne,ybOne = first(dl)
xbOne.shape,ybOne.shape

(torch.Size([256, 784]), torch.Size([256, 1]))

In [17]:
# test cell: Check training data is shuffled
print(xbOne[:10])
print(ybOne[:10])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[7],
        [7],
        [2],
        [5],
        [0],
        [7],
        [3],
        [7],
        [8],
        [7]])


<h1>Define architecture, parameters, loss, metrics</h1>

In [18]:
class BasicOptim:
    def __init__(self,params,lr): self.params,self.lr = list(params),lr

    def step(self, *args, **kwargs):
        for p in self.params: p.data -= p.grad.data * self.lr

    def zero_grad(self, *args, **kwargs):
        for p in self.params: p.grad = None

In [19]:
def initParam(size, std=0.1): #Values over ~0.16 cause validation accs to get stuck at 0.0
    return (torch.randn(size)*std).requires_grad_()

def mnistModel(inputs): #Remember to adjust according to parameter depth
    acts = inputs@w1 + b1
    acts = acts.max(tensor(0.0))
    acts = acts@w2 + b2
    acts = acts.max(tensor(0.0))
    acts = acts@w3 + b3
    acts = acts.max(tensor(0.0))
    acts = acts@w4 + b4
    return acts

def mnistLoss(acts, targs): #Softmax to CELoss eventually
    preds = -torch.log_softmax(acts, dim=1)
    idx = range(preds.size()[0])
    loss = preds[idx,targs].mean()
    return loss

In [20]:
def calc_grad(inputs, labels, model):
    acts = model(inputs)
    loss = mnistLoss(acts, labels[:,0])
    loss.backward()
    
def train_epoch(model):
    for inputs,labels in dl:
        calc_grad(inputs, labels, model)
        opt.step()
        opt.zero_grad()
        
def batch_accuracy(acts, labels): #Are these nested indices a bad idea, consider one hot encoding/embedding?
    preds = -torch.log_softmax(acts, dim=1) #Not summing to 1 across relevant axis
    pred_idx = range(preds.size()[0])
    correct = [preds[entry].min() == preds[entry,labels[entry]] for entry in pred_idx] #Because -log, should I min() instead of max()?
    return torch.Tensor(correct).float().mean()

def validate_epoch(model):
    accs = [batch_accuracy(model(inputs), labels) for inputs,labels in valid_dl]
    return round(torch.stack(accs).mean().item(), 4)

def train_model(model, epochs):
    for i in range(epochs):
        train_epoch(model)
        print(validate_epoch(model), end=' ')

# Initialise parameters and train model

In [21]:
# 4 layer model: [784, 500, 200, 80, 10]
w1 = initParam((28*28,500))
b1 = initParam(500)
w2 = initParam((500,200))
b2 = initParam(200)
w3 = initParam((200,80))
b3 = initParam(80)
w4 = initParam((80,10))
b4 = initParam(10)
params = list([w1,b1,w2,b2,w3,b3,w4,b4])

lr = 1e-1

opt = BasicOptim(params, lr)

In [22]:
learner = train_model(mnistModel, 6)

0.9008 0.9354 0.9538 0.9591 0.9527 0.9412 

# Experiment Cells

In [23]:
#test cell
acts1 = xbOne@w1 + b1
acts2 = acts1.max(tensor(0.0))
acts3 = acts2@w2 + b2
acts4 = acts3.max(tensor(0.0))
acts5 = acts4@w3 + b3
acts6 = acts5.max(tensor(0.0))
acts7 = acts6@w4 + b4

sm_preds = -torch.log_softmax(acts7, dim=-1)
pred_idx = range(256)


loss = sm_preds[pred_idx,ybOne].mean()

#Regularise the activations to stop over/underflow
#Regularisation/Weight decay can be found in 08_collab

#xbOne.size()
acts7.size()
#torch.softmax(acts3, dim=0)[29]
#torch.log(torch.softmax(acts3, dim=0)).size()[0]
#loss

#torch.softmax(acts7, dim=1)[5].sum()
#sm_preds[5].sum()
#correct = torch.Tensor([sm_preds[entry].max() == sm_preds[entry,ybOne[entry]] for entry in pred_idx])
#correct.mean()

torch.Size([256, 10])

In [24]:
axis = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).float()
torch.softmax(axis,dim=0).sum()

tensor(1.0000)

# So:<br>
I am summing the softmaxes properly; they do sum to 1<br>
I THINK I am updating the parameters properly using grad times lr<br>
But for some reason the weights aren't actually updating the way I would expect, because the loss is hovering around -log(0.1)=2.3